resolver: lts-7.15
packages:
  - '.'
  - location:
      git: https://github.com/lpeterse/haskell-socket.git
      commit: 142561b7daacc35d1e8ddce22363bea73b8c281e
extra-deps:
  - socket-0.8.0.0
  - tls-1.3.9
  - cryptonite-0.21
  - QuickCheck-2.9.2
flags: {}
extra-package-dbs: []
